### ISSUE TITLE
Add support for SigV4 authentication plugin

### ISSUE THREAD

**Issue by feedhandler** [aws-samples/amazon-keyspaces-toolkit#5]
Hi, please could you add some notes to readme about how to use the SigV4 authentication plugin?
Thanks

**Comment by michaelraney** [comment]
hi @feedhandler 

Just added a version of cqlsh with sigv4 support and updated the readme. 

# Using Sigv4 Authentication with cqlsh
The toolkit contains a version of cqlsh that extends Authentication functionality to leverage the [Sigv4 athentication plugin for the Python Cassandra driver](https://github.com/aws/aws-sigv4-auth-cassandra-python-driver-plugin). This plugin enables IAM users, roles, and federated identities to add authentication information to Amazon Keyspaces (for Apache Cassandra) API requests using the AWS Signature Version 4 Process (SigV4). You can leverage this functionality by passing "cqlsh-expansion" to the ```--entrypoint``` docker run parameter, and the ```--sigv4``` flag to the cqlsh-expansion process. You can use the docker container host's credentials by mounting the AWS CLI configuration directory to the container using the mount command ```-v```. If your AWS configuration is stored in ~/.aws then the Docker mount command would be `-v ~/.aws:/root/.aws`.

```sh
docker build --tag amazon/keyspaces-toolkit --build-arg CLI_VERSION=latest https://github.com/aws-samples/amazon-keyspaces-toolkit.git

docker run -ti --rm -v ~/.aws:/root/.aws --entrypoint cqlsh-expansion amazon/keyspaces-toolkit cassandra.us-east-1.amazonaws.com --ssl --sigv4
```

**Comment by feedhandler** [comment]
Thanks
